/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "configuration.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(my_Configuration, my_Configuration, AUTO)



